import React, { useState, useEffect } from "react";
import apiService from "../services/apiServices";
import {
  FiActivity,
  FiTrendingUp,
  FiTrendingDown,
  FiClock,
  FiSearch,
  FiChevronDown,
  FiChevronRight,
  FiCalendar
} from "react-icons/fi";

const SymbolLogo = ({ symbol }) => {
  // Simple deterministic color generation based on symbol string
  const colors = ["#ef4444", "#f97316", "#f59e0b", "#10b981", "#3b82f6", "#6366f1", "#8b5cf6", "#ec4899"];
  const charCode = symbol.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
  const color = colors[charCode % colors.length];

  return (
    <div
      style={{
        width: 32,
        height: 32,
        borderRadius: "50%",
        backgroundColor: color,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        color: "#fff",
        fontWeight: "bold",
        fontSize: 14,
        marginRight: 12
      }}
    >
      {symbol.charAt(0).toUpperCase()}
    </div>
  );
};

export default function Signals() {
  const [signals, setSignals] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState("");

  const fetchSignals = async () => {
    try {
      const response = await apiService.get("/api/strategy/scanner-dashboard");
      console.log("Scanner Dashboard API Response:", response);
      
      // Handle different possible response structures
      if (response && Array.isArray(response)) {
        setSignals(response);
      } else if (response && response.data && Array.isArray(response.data)) {
        setSignals(response.data);
      } else if (response && response.data && response.data.data && Array.isArray(response.data.data)) {
        setSignals(response.data.data);
      } else {
        console.warn("Unexpected response format:", response);
      }
    } catch (error) {
      console.error("Failed to fetch signals:", error);
    } finally {
      setLoading(false);
    }
  };

  // useEffect(() => {
  //   fetchSignals();
  //   // Poll every 5 minutes (300000ms)
  //   const intervalId = setInterval(fetchSignals, 300000);
  //   return () => clearInterval(intervalId);
  // }, []);

  const filteredSignals = signals.filter(signal => 
    signal.symbol.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const totalSignals = signals.length;
  const buySignals = signals.filter(s => s.signalType?.toUpperCase() === "BUY").length;
  const sellSignals = signals.filter(s => s.signalType?.toUpperCase() === "SELL").length;
  const buyPercentage = totalSignals > 0 ? Math.round((buySignals / totalSignals) * 100) : 0;
  const sellPercentage = totalSignals > 0 ? Math.round((sellSignals / totalSignals) * 100) : 0;

  const lastUpdated = signals.length > 0 
    ? new Date(Math.max(...signals.map(s => new Date(s.updatedAt).getTime()))) 
    : new Date();

  return (
    <div style={{ minHeight: "100vh", backgroundColor: "var(--bg-primary)", color: "var(--text-primary)", padding: "32px", fontFamily: "Inter, sans-serif" }}>
      <div style={{ maxWidth: 1200, margin: "0 auto" }}>
        
        {/* Header */}
        <div style={{ marginBottom: 32 }}>
          <h1 style={{ fontSize: 24, fontWeight: 600, marginBottom: 8, color: "var(--text-primary)" }}>Trading Signals</h1>
          <p style={{ color: "var(--text-secondary)", fontSize: 14 }}>Real-time trading signals generated by our AI-powered indicators</p>
        </div>

        {/* Stats Grid */}
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: 24, marginBottom: 32 }}>
          
          {/* Total Signals */}
          <div style={{ backgroundColor: "var(--bg-secondary)", border: "1px solid var(--border-color)", borderRadius: 12, padding: 24, display: "flex", alignItems: "center", gap: 16 }}>
            <div style={{ width: 48, height: 48, borderRadius: "50%", backgroundColor: "rgba(59, 130, 246, 0.1)", display: "flex", alignItems: "center", justifyContent: "center", color: "#3b82f6" }}>
              <FiActivity size={24} />
            </div>
            <div>
              <p style={{ color: "var(--text-secondary)", fontSize: 13, marginBottom: 4 }}>Total Signals</p>
              <div style={{ fontSize: 24, fontWeight: 600, marginBottom: 4 }}>{totalSignals}</div>
              <div style={{ color: "var(--text-secondary)", fontSize: 12, display: "flex", alignItems: "center", gap: 4 }}>
                <FiCalendar size={12} /> Today
              </div>
            </div>
          </div>

          {/* Buy Signals */}
          <div style={{ backgroundColor: "var(--bg-secondary)", border: "1px solid var(--border-color)", borderRadius: 12, padding: 24, display: "flex", alignItems: "center", gap: 16 }}>
            <div style={{ width: 48, height: 48, borderRadius: "50%", backgroundColor: "rgba(34, 197, 94, 0.1)", display: "flex", alignItems: "center", justifyContent: "center", color: "#22c55e" }}>
              <FiTrendingUp size={24} />
            </div>
            <div>
              <p style={{ color: "var(--text-secondary)", fontSize: 13, marginBottom: 4 }}>Buy Signals</p>
              <div style={{ fontSize: 24, fontWeight: 600, marginBottom: 4 }}>{buySignals}</div>
              <div style={{ color: "var(--text-secondary)", fontSize: 12 }}>
                <span style={{ color: "#22c55e", fontWeight: 500 }}>{buyPercentage}%</span> of total
              </div>
            </div>
          </div>

          {/* Sell Signals */}
          <div style={{ backgroundColor: "var(--bg-secondary)", border: "1px solid var(--border-color)", borderRadius: 12, padding: 24, display: "flex", alignItems: "center", gap: 16 }}>
            <div style={{ width: 48, height: 48, borderRadius: "50%", backgroundColor: "rgba(239, 68, 68, 0.1)", display: "flex", alignItems: "center", justifyContent: "center", color: "#ef4444" }}>
              <FiTrendingDown size={24} />
            </div>
            <div>
              <p style={{ color: "var(--text-secondary)", fontSize: 13, marginBottom: 4 }}>Sell Signals</p>
              <div style={{ fontSize: 24, fontWeight: 600, marginBottom: 4 }}>{sellSignals}</div>
              <div style={{ color: "var(--text-secondary)", fontSize: 12 }}>
                <span style={{ color: "#ef4444", fontWeight: 500 }}>{sellPercentage}%</span> of total
              </div>
            </div>
          </div>

          {/* Last Updated */}
          <div style={{ backgroundColor: "var(--bg-secondary)", border: "1px solid var(--border-color)", borderRadius: 12, padding: 24, display: "flex", alignItems: "center", gap: 16 }}>
            <div style={{ width: 48, height: 48, borderRadius: "50%", backgroundColor: "rgba(168, 85, 247, 0.1)", display: "flex", alignItems: "center", justifyContent: "center", color: "#a855f7" }}>
              <FiClock size={24} />
            </div>
            <div>
              <p style={{ color: "var(--text-secondary)", fontSize: 13, marginBottom: 4 }}>Last Updated</p>
              <div style={{ fontSize: 20, fontWeight: 600, marginBottom: 4 }}>
                {lastUpdated.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', second: '2-digit' })}
              </div>
              <div style={{ color: "var(--text-secondary)", fontSize: 12 }}>
                {lastUpdated.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })}
              </div>
            </div>
          </div>

        </div>

        {/* Main Content Area */}
        <div style={{ backgroundColor: "var(--bg-secondary)", border: "1px solid var(--border-color)", borderRadius: 12, overflow: "hidden" }}>
          
          {/* Toolbar */}
          <div style={{ padding: 20, display: "flex", justifyContent: "space-between", alignItems: "center", borderBottom: "1px solid var(--border-color)", flexWrap: "wrap", gap: 16 }}>
            
            {/* Search */}
            <div style={{ position: "relative", width: "100%", maxWidth: 300 }}>
              <div style={{ position: "absolute", left: 12, top: "50%", transform: "translateY(-50%)", color: "var(--text-secondary)" }}>
                <FiSearch size={16} />
              </div>
              <input 
                type="text" 
                placeholder="Search symbol..." 
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                style={{ 
                  width: "100%", 
                  backgroundColor: "rgba(0,0,0,0.2)", 
                  border: "1px solid var(--border-color)", 
                  borderRadius: 6, 
                  padding: "8px 12px 8px 36px",
                  color: "var(--text-primary)",
                  outline: "none",
                  fontSize: 14
                }} 
              />
            </div>

            {/* Filters */}
            <div style={{ display: "flex", gap: 12 }}>
              <button style={{ backgroundColor: "transparent", border: "1px solid var(--border-color)", borderRadius: 6, padding: "8px 16px", color: "var(--text-primary)", fontSize: 14, display: "flex", alignItems: "center", gap: 8, cursor: "pointer" }}>
                All Signals <FiChevronDown />
              </button>
              <button style={{ backgroundColor: "transparent", border: "1px solid var(--border-color)", borderRadius: 6, padding: "8px 16px", color: "var(--text-primary)", fontSize: 14, display: "flex", alignItems: "center", gap: 8, cursor: "pointer" }}>
                All Types <FiChevronDown />
              </button>
              <button style={{ backgroundColor: "transparent", border: "1px solid var(--border-color)", borderRadius: 6, padding: "8px 16px", color: "var(--text-primary)", fontSize: 14, display: "flex", alignItems: "center", gap: 8, cursor: "pointer" }}>
                <FiCalendar /> Today <FiChevronDown />
              </button>
            </div>
          </div>

          {/* Table */}
          <div style={{ overflowX: "auto" }}>
            <table style={{ width: "100%", borderCollapse: "collapse" }}>
              <thead>
                <tr style={{ backgroundColor: "rgba(0,0,0,0.1)", borderBottom: "1px solid var(--border-color)" }}>
                  <th style={{ padding: "16px 20px", textAlign: "left", fontSize: 12, color: "var(--text-secondary)", fontWeight: 500 }}>#</th>
                  <th style={{ padding: "16px 20px", textAlign: "left", fontSize: 12, color: "var(--text-secondary)", fontWeight: 500 }}>SYMBOL</th>
                  <th style={{ padding: "16px 20px", textAlign: "left", fontSize: 12, color: "var(--text-secondary)", fontWeight: 500 }}>SIGNAL TYPE</th>
                  <th style={{ padding: "16px 20px", textAlign: "left", fontSize: 12, color: "var(--text-secondary)", fontWeight: 500 }}>INDICATOR VALUES</th>
                  <th style={{ padding: "16px 20px", textAlign: "left", fontSize: 12, color: "var(--text-secondary)", fontWeight: 500 }}>TIMESTAMP</th>
                  <th style={{ padding: "16px 20px", textAlign: "left", fontSize: 12, color: "var(--text-secondary)", fontWeight: 500 }}>UPDATED AT</th>
                  <th style={{ padding: "16px 20px" }}></th>
                </tr>
              </thead>
              <tbody>
                {loading ? (
                  <tr>
                    <td colSpan="7" style={{ padding: 40, textAlign: "center", color: "var(--text-secondary)" }}>Loading signals...</td>
                  </tr>
                ) : filteredSignals.length === 0 ? (
                  <tr>
                    <td colSpan="7" style={{ padding: 40, textAlign: "center", color: "var(--text-secondary)" }}>No signals found</td>
                  </tr>
                ) : (
                  filteredSignals.map((signal, index) => {
                    const isBuy = signal.signalType?.toUpperCase() === "BUY";
                    
                    let indicatorVals = signal.indicatorValues;
                    if (typeof indicatorVals === 'string') {
                      try { indicatorVals = JSON.parse(indicatorVals); } catch(e) {}
                    }

                    const formatDt = (dtString) => {
                      if (!dtString) return { date: "--", time: "--" };
                      const d = new Date(dtString);
                      return {
                        date: d.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }),
                        time: d.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', second: '2-digit' })
                      };
                    };

                    const ts = formatDt(signal.timestamp);
                    const upd = formatDt(signal.updatedAt);

                    return (
                      <tr key={signal.id} style={{ borderBottom: "1px solid var(--border-color)", transition: "background-color 0.2s" }} onMouseOver={e => e.currentTarget.style.backgroundColor = "rgba(255,255,255,0.02)"} onMouseOut={e => e.currentTarget.style.backgroundColor = "transparent"}>
                        <td style={{ padding: "16px 20px", color: "var(--text-secondary)", fontSize: 14 }}>{signal.id}</td>
                        
                        <td style={{ padding: "16px 20px" }}>
                          <div style={{ display: "flex", alignItems: "center" }}>
                            <SymbolLogo symbol={signal.symbol} />
                            <span style={{ fontWeight: 500, fontSize: 14 }}>{signal.symbol}</span>
                          </div>
                        </td>
                        
                        <td style={{ padding: "16px 20px" }}>
                          <div style={{
                            display: "inline-flex",
                            alignItems: "center",
                            gap: 6,
                            padding: "4px 12px",
                            borderRadius: 100,
                            fontSize: 12,
                            fontWeight: 500,
                            backgroundColor: isBuy ? "rgba(34, 197, 94, 0.1)" : "rgba(239, 68, 68, 0.1)",
                            color: isBuy ? "#22c55e" : "#ef4444",
                            border: `1px solid ${isBuy ? "rgba(34, 197, 94, 0.2)" : "rgba(239, 68, 68, 0.2)"}`
                          }}>
                            {isBuy ? <FiTrendingUp size={14} /> : <FiTrendingDown size={14} />}
                            {isBuy ? "BUY" : "SELL"}
                          </div>
                        </td>
                        
                        <td style={{ padding: "16px 20px", fontSize: 13, color: "var(--text-secondary)" }}>
                          <div style={{ marginBottom: 4 }}>Index: <span style={{ color: "var(--text-primary)" }}>{indicatorVals?.index || "--"}</span></div>
                          <div>Type: <span style={{ color: isBuy ? "#22c55e" : "#ef4444", fontWeight: 500 }}>{indicatorVals?.type || "--"}</span></div>
                        </td>
                        
                        <td style={{ padding: "16px 20px", fontSize: 13, color: "var(--text-secondary)" }}>
                          <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 4 }}>
                            <FiClock size={12} /> {ts.date}
                          </div>
                          <div style={{ marginLeft: 18 }}>{ts.time}</div>
                        </td>
                        
                        <td style={{ padding: "16px 20px", fontSize: 13, color: "var(--text-secondary)" }}>
                          <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 4 }}>
                            <FiClock size={12} /> {upd.date}
                          </div>
                          <div style={{ marginLeft: 18 }}>{upd.time}</div>
                        </td>
                        
                        <td style={{ padding: "16px 20px", textAlign: "right", color: "var(--text-secondary)" }}>
                          <button style={{ background: "none", border: "none", color: "inherit", cursor: "pointer", padding: 4 }}>
                            <FiChevronRight size={18} />
                          </button>
                        </td>
                      </tr>
                    );
                  })
                )}
              </tbody>
            </table>
          </div>

          {/* Pagination */}
          <div style={{ padding: 20, display: "flex", justifyContent: "center", borderTop: "1px solid var(--border-color)" }}>
            <div style={{ display: "flex", gap: 8 }}>
              <button style={{ width: 32, height: 32, display: "flex", alignItems: "center", justifyContent: "center", borderRadius: 6, border: "1px solid var(--border-color)", backgroundColor: "transparent", color: "var(--text-secondary)", cursor: "pointer" }}>
                &lt;
              </button>
              <button style={{ width: 32, height: 32, display: "flex", alignItems: "center", justifyContent: "center", borderRadius: 6, border: "1px solid #3b82f6", backgroundColor: "#3b82f6", color: "#fff", cursor: "pointer" }}>
                1
              </button>
              <button style={{ width: 32, height: 32, display: "flex", alignItems: "center", justifyContent: "center", borderRadius: 6, border: "1px solid var(--border-color)", backgroundColor: "transparent", color: "var(--text-secondary)", cursor: "pointer" }}>
                &gt;
              </button>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
}
